import 'package:bio_attend/app/utils/constant/app_strings.dart';

final Map<String, String> ar = {
  AppStrings.welcomemsg: 'مرحبًا بك في تطبيق الموارد البشرية',
  AppStrings.siteURL: 'رابط الموقع',
  AppStrings.companySiteUrl: 'أدخل رابط موقعك',
  AppStrings.continuebutton: 'استمرار',
  AppStrings.appName: 'الحضور البيومتري',
  AppStrings.userName: 'اسم المستخدم',
  AppStrings.enterYourUsername: 'أدخل اسم المستخدم الخاص بك',
  AppStrings.password: 'كلمة المرور',
  AppStrings.enterYourPassword: 'أدخل كلمة المرور الخاصة بك',
  AppStrings.login: 'تسجيل الدخول',
  AppStrings.attendancePgTitle: 'صفحة الحضور',
  AppStrings.checkIn: 'تسجيل الدخول',
  AppStrings.checkOut: 'تسجيل انصراف',
  AppStrings.getMoreClose: 'اقترب أكثر من المكتب!',
  AppStrings.attendance: 'الحضور',
  AppStrings.leave: 'مغادرة',
  AppStrings.authMessage: 'امسح بصمة إصبعك للمصادقة',
  AppStrings.editSiteUrl: "تعديل رابط الموقع",
  AppStrings.attendancereport: 'تقرير الحضور',
  AppStrings.noDataFound: 'لا يوجد بيانات',
  AppStrings.enapleLocation: 'يرجى تفعيل خدمات الموقع لاكمال هذه العملية',
  AppStrings.goToSetting: 'الذهاب إلى الاعدادات',
  AppStrings.attendanceCheckin: 'تسجيل الحضور',
  AppStrings.enableAccess: "تفعيل الوصول للموقع",
  AppStrings.ureTooFar: "أنت بعيد جدًا عن المكتب لتسجيل الدخول.",
  AppStrings.authErrorOccured: "حدث خطأ في المصادقة.",
  AppStrings.processCompleted: "العملية تمت بنجاح.",
  AppStrings.checkinErrorOcuured: "حدث خطأ في التسجيل.",
  AppStrings.failedToFetchBranch : "لم يتم العثور علي الفروع.",
  "Failed to get current location.": "فشل في الحصول على الموقع الحالي.",
  "Location services are disabled.": "خدمات الموقع معطلة.",
  "No location data available for check-in.":
      "لا تتوفر بيانات الموقع لتسجيل الدخول.",
  "No branch selected.": "لم يتم اختيار أي فرع.",
  "Biometric authentication failed.": "فشلت المصادقة البيومترية.",
  'server_error': 'خطأ في الخادم',
  'invalid_server': "خطأ في رابط الموقع",
  "an_error_occurred": "حدث خطأ يرجي المحاولة مرة أخرى",
  'network_error': 'خطأ في الشبكة',
  'logout_error': 'خطأ في تسجيل الخروج',
  'logout_network_error': 'خطأ في الشبكة أثناء تسجيل الخروج',
  "Biometric authentication is not available on this device.":
      "المصادقة البيومترية غير متوفرة على هذا الجهاز.",
  'Authentication failed. Please try again.':
      'فشل المصادقة. الرجاء المحاولة مرة أخرى.',
  'Please enter your username': 'الرجاء أدخال اسم المستخدم',
  'Please enter your password': 'الرجاء أدخال كلمة المرور',
  'Password must be at least 6 characters':
      'كلمة المرور يجب أن تكون على الاقل 6 حروف',
};
