import '../utils/constant/app_strings.dart';

// English translations
final Map<String, String> en = {
  AppStrings.welcomemsg: 'Welcome to HR App',
  AppStrings.siteURL: 'Site Url',
  AppStrings.companySiteUrl: 'Enter your site url',
  AppStrings.continuebutton: 'Continue',
  AppStrings.appName: 'Bio Attendance',
  AppStrings.userName: 'userName',
  AppStrings.enterYourUsername: 'enter_your_username',
  AppStrings.password: 'password',
  AppStrings.enterYourPassword: 'enter_your_password',
  AppStrings.login: 'login',
  AppStrings.attendancePgTitle: 'Attendance Page',
  AppStrings.checkIn: 'Check In',
  AppStrings.checkOut: 'Check Out',
  AppStrings.getMoreClose: 'Get more close to office!',
  AppStrings.attendance: 'Attendance',
  AppStrings.leave: 'Leave',
  AppStrings.authMessage: 'Scan your fingerprint to authenticate',
  AppStrings.editSiteUrl: "Edit site URL",
  AppStrings.attendancereport: 'Attendance Report',
  AppStrings.noDataFound: 'No Data Found',
  AppStrings.enapleLocation: 'Please enable location to complete this process',
  AppStrings.goToSetting: 'Go to Settings',
  AppStrings.enableAccess: 'Enable Location Access',
  AppStrings.attendanceCheckin: "Attendance Checkin",
  "Failed to get current location.": "Failed to get current location.",
  "No location data available for check-in.":
      "No location data available for check-in.",
  'No branch selected.': 'No branch selected.',
  AppStrings.ureTooFar: 'You are too far from the office to check-in.',
  AppStrings.authErrorOccured: 'Authentication error occured.',
  AppStrings.processCompleted: 'Process completed successfully.',
  AppStrings.checkinErrorOcuured: 'Check-in error occured.',
  AppStrings.failedToFetchBranch: 'Failed to fetch branches.',
  'Biometric authentication failed.': 'Biometric authentication failed.',
  "Location services are disabled.": "Location services are disabled.",
  "server_error": "Server error: {code}",
  "an_error_occurred": "An error occurred Try again",
  "invalid_server": "Invalid URL",
  "network_error": "Network error",
  "logout_error": "Error logging out user",
  "logout_network_error": "Network error during logout: {error}",
  "Biometric authentication is not available on this device.":
      "Biometric authentication is not available on this device.",
  'Authentication failed. Please try again.':
      'Authentication failed. Please try again.',
  'Please enter your username': 'Please enter your username',
  'Please enter your password': 'Please enter your password',
  'Password must be at least 6 characters':
      'Password must be at least 6 characters',
};
